### ISSUE TITLE
Bravi bel lavoro, tenendo conto che avete Siliqua

### ISSUE THREAD

**Issue by Zexal0807** [iamousseni/chitchat#1]
:)

by Zexal0807

**Comment by EltarSilence** [comment]
Ma sì, in fondo non è così male. Bravi, bel frontend

**Comment by iamousseni** [comment]
Grazie!

**Comment by Zexal0807** [comment]
Come era prevedibile avete un bel FrontEnd, ma ricordate che non è che tutto quello che è marrone è nutella

**Comment by iamousseni** [comment]
AHAHAHHAHA tranquillo inizierai a diventare code-sexual appena vedrai il nostro back

**Comment by Zexal0807** [comment]
Non credo, esiste una sola persona che produce codice da backend eccitante, il suo nome inizia con Zex e finisce con al0807, non so se lo conosci

**Comment by iamousseni** [comment]
Mai sentito...probabilmente avrai sentito Ousseni Bara, non so si dice in giro che non sia male...
