### ISSUE TITLE
Le bolle si comportano in modo strano

### ISSUE THREAD

**Issue by ElCapitanGoldrex** [iamousseni/chitchat#4]
Just look at this
<img width="757" alt="jifaffan" src="https://user-images.githubusercontent.com/50243353/58077829-9de37900-7bad-11e9-991d-aac6b898117b.png">

**Comment by iamousseni** [comment]
Risolto. IL problema si presentava solo su chrome per via di una diversa gestione tra firefox e chrome riguardo la regola display: flex
