### ISSUE TITLE
La ricerca lascia chat duplicate

### ISSUE THREAD

**Issue by ivanrava** [iamousseni/chitchat#5]
### Come riprodurre

1. cercare qualunque cosa dalla barra di ricerca
2. cancellare il testo inserito
3. rimangono delle chat duplicate

### Soluzione proposta

Teoricamente l'utente dovrebbe ritornare alla view principale delle chat, quasi come un reload della pagina. Il file js/slideChatAjax.js potrebbe essere d'aiuto?

**Comment by iamousseni** [comment]
Fixato con ecelleza!

**Comment by iamousseni** [comment]
grazie a me il telecomunicante muahahaha

**Comment by ivanrava** [comment]
_Fixato_ per modo di dire. Cancellando la query dalla barra di ricerca ricompaiono normalmente le chat, ma non è più possibile interagirci (tipo con un click)
